PLF-8434: Revert "Migrate Web3js to version 1.2.1" (#14)
An error is logged in console when opening a Wiki page:

TypeError: _ is not a constructorbabelpolyfill--min.js:6:45723
[145]< http://localhost:8080/portal/scripts/5.3.0-M20/SHARED/babelpolyfill--min.js:6
s http://localhost:8080/portal/scripts/5.3.0-M20/SHARED/babelpolyfill--min.js:6
s http://localhost:8080/portal/scripts/5.3.0-M20/SHARED/babelpolyfill--min.js:6

This is due to Wallet Addon version 1.0.0-M20 where babelpolyfill is added as dependency, see:
https://github.com/exoplatform/wallet/blob/develop/wallet-webapps-common/src/main/webapp/WEB-INF/gatein-resources.xml#L147

The commit is reverted until a better solution for babelpolyfill integration is made.